pipeline {
    agent { label 'AGENT-1'}
    environment {
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = ''
        aws_account_id = '444152781209'
        //ACC_ID = ''
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit:'MINUTES')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    } 
    
    stages {
        stage('init') {
            steps {
                script {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan
                    """
                }
                    
                }
            }

        }

         stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                script {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                    """
                }
                    
                }
            }

        }
        stage('Trigger SG'){
            when{
                expression {params.ACTION == 'apply'}
            }
            steps{
                build job: '10-sg', parameters: [string(name:'ACTION', value: 'apply')], propagate: true
            }
        }
         
    }
    post {
            always {
                echo 'i will run if it is success or fail'
                deleteDir()
            }
            failure {
                echo 'i will run when pipeline fails'
            }
            success {
                echo 'i will run when pipeline success'
            }
        }
    }


