pipeline {
    agent { label 'AGENT-1' }
    environment {
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = ''
        aws_account_id = '444152781209'
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                            terraform plan
                        """
                    }
                }
            }
        }

        stage('apply') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }

        stage('Parallel Stages') {
            when {
                expression { params.ACTION == 'apply' }
            }
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        build job: '20-Bastion', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
                    }
                }
                stage('Trigger rds') {
                    steps {
                        build job: '50-rds', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
                    }
                }
                stage('Trigger eks') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
                    }
                }
                stage('Trigger ecr') {
                    steps {
                        build job: '60-ecr', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
                    }
                }
            }
        }
        stage('equence stages'){
            stages {
                stage('70-acm'){
                    steps {
                        build job: '70-acm', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('60-ingress-alb'){
                    steps {
                        build job: '60-ingress-alb', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }

            }
        }
    }   

    post {
        always {
            echo 'i will run if it is success or fail'
            deleteDir()
        }
        failure {
            echo 'i will run when pipeline fails'
        }
        success {
            echo 'i will run when pipeline success'
        }
    }
}